### ISSUE TITLE
how to use this class?

### ISSUE THREAD

**Issue by natxopedreira** [tallavi/ofxGestures#2]
Hi

Will this work on windows, right now im getting touchPoints in an of app running win 8.1 and want to get gestures..... So i found your addon but i was not able to get my head on how to use this.

Thanks!

**Comment by tallavi** [comment]
Hi!

I never tried it on windows, but it is tested on iOS and Android. It doesn't contain ANY platform specific code so in theory it should work perfectly on all OF supported platforms.

It does its thing by listening to the "simple" touch events as exposed by of (touch down/move/ended),  and when it recognizes a gesture, it throws an event.

I highly recommend you'll pull and use the branch "more_gestures", which as the name implies, has more gestures, and also a redesigned (breaking) interface. Soon this branch will be merged into master, so I'll demonstrate using this branch updated interface.

When starting up, register to the gestures with something like that:

```
    ofAddListener(ofxGestures::get().panEvent, this, &MapView::onPanGestureEvent);
    ofAddListener(ofxGestures::get().panEndedEvent, this, &MapView::onPanGestureEventEnded);
    ofAddListener(ofxGestures::get().pinchEvent, this, &MapView::onPinchGestureEvent);
    ofAddListener(ofxGestures::get().pinchEndedEvent, this, &MapView::onPinchGestureEventEnded);
    ofAddListener(ofxGestures::get().tapEvent, this, &MapView::onTapGestureEvent);
    ofAddListener(ofxGestures::get().longPressEvent, this, &MapView::onLongPressGestureEvent);
```

You can register to only some of the gestures of course.

If relevant, have the deregistration when the class is terminated (not relevant to simple apps):

```
    ofRemoveListener(ofxGestures::get().panEvent, this, &MapView::onPanGestureEvent);
    ofRemoveListener(ofxGestures::get().panEndedEvent, this, &MapView::onPanGestureEventEnded);
    ofRemoveListener(ofxGestures::get().pinchEvent, this, &MapView::onPinchGestureEvent);
    ofRemoveListener(ofxGestures::get().pinchEndedEvent, this, &MapView::onPinchGestureEventEnded);
    ofRemoveListener(ofxGestures::get().tapEvent, this, &MapView::onTapGestureEvent);
    ofRemoveListener(ofxGestures::get().longPressEvent, this, &MapView::onLongPressGestureEvent);

```

"MapView" in this case is your ofApp class or something.

Check the definition of the events to know what the signature needs to be. For example, for  onPanGestureEvent it needs to be:

`void MapView::onPanGestureEvent(const ofxGestures::PanEventArgs &panEventArgs)`

And then handle the different callbacks as you want, check out the event args members to see what you can know about each gesture.

That's about it. Hope it helps. Notice that this branch is currently under active development and there's no guarantee that the interface won't break soon. If that's a problem, I recommend you'll fork to freeze the version you use to the current version.

If you have any questions, do ask.

**Comment by natxopedreira** [comment]
Thanks!!!

Ok, i see where i was getting wrong, i will use the branch "more_gestures" and tell you about

**Comment by natxopedreira** [comment]
Well, i must be doing something else wrong because i get no callbacks from gestures.

im getting from the console, touchDown, touchMoved and touchUp but no response from gestures.

Im using your "more_gestures" branch, i declare on setup, for example:

`ofAddListener(ofxGestures::get().panEvent, this, &ofApp::onPanGestureEvent);`

and the function its 

```
void ofApp::onPanGestureEvent(const ofxGestures::PanEventArgs &p){
 cout << "panInit" << Lendl
}
```

But this never get called

I also need to call ofxGestures::get().start() before declaring the callbacks

Im missing something?¿

**Comment by natxopedreira** [comment]
Im seeing that the touch.id coming from windows has an incremental value that never reset so the id increments.

Maybe this its related

**Comment by tallavi** [comment]
Not sure I understand your last comment. You're saying that in windows the touch id of the first finger is not 0? If that's the case, that is definately the problem, as ofxGestures assumes that.

You're right about calling start() in setup, before or after you register callbacks. It's a new requirement from yesterday when we figured that we can't know that automatically. We're still working on it to find a better solution.

Can you put a break point in touch down/move inside ofxGestures to make sure the touches are being received there?

And can you write the touch ids you are getting?

**Comment by natxopedreira** [comment]
Yep, on windows the id of  the touch its a incremental value. So the first its not 0 and the second its not 1......

Im almost sure that the touches are beinng received in the ofxGestures code because i put a cout msg inside and get that on the console.

Im getting values for the touch id like 1600.. 1601... 1602 and go on...... I read that in oF the touch id its like the touch number so first its always 0 and second its always 1.......

Im working right now on this so if you want to test something.... tell me

**Comment by tallavi** [comment]
As I mentioned, the touches supposed to be 0,1,2 etc, and I take this as a fact. It works like this in iOS and Android, so I built this thing around this fact.

For example, in pan gesture, I look at touch 0. In pinch, I look at 0+1. 

I see two ways around it.

1) Change the openFrameworks code to have serial zero based touch ids. Android and iOS have such code. Basically it revolves around looking at the ids as they come, and putting them in a map with the  zero based ids as indexes. The iOS code for example is at the class ofxiOSEAGLView.mm if you want to have a look.

2) Change ofxGestures so that it can handle arbitrary touch ids as they come. That sounds more convoluted solution if you ask me.

Perhaps you should ask in the forum for some advise from veteran ofWindows gurus?

**Comment by natxopedreira** [comment]
Thanks for explaining, i will try to think in something and also i will ask in the forum.
